In [ ]:
!mkdir -p ~/.kaggle
!echo KGAT_26d0b434eeea07da0f48bb9e6cee272e > ~/.kaggle/access_token
!chmod 600 ~/.kaggle/access_token
!pip install -q kaggle

In [ ]:
!kaggle datasets list -s "lending club"

Warning: Looks like you're using an outdated `kaggle` version (installed: 2.0.2), please consider upgrading to the latest version (2.2.2)
ref                                                             title                                                  size  lastUpdated                 downloadCount  voteCount  usabilityRating
--------------------------------------------------------------  -----------------------------------------------  ----------  --------------------------  -------------  ---------  ---------------
wordsforthewise/lending-club                                    All Lending Club loan data                       1356507910  2019-04-10 18:03:34.347000         112926        924  0.75
adarshsng/lending-club-loan-data-csv                            Lending Club Loan Data                            355544101  2021-06-17 11:06:05.723000          24888        156  0.9411765
ethon0426/lending-club-20072020q1                               Lending Club 2007-2020Q3                          505408012  2020-12-15 18:15:28.060000          20475        127  0.9411765
urstrulyvikas/lending-club-loan-data-analysis                   Lending Club Loan Data Analysis                      218250  2021-05-24 03:38:11.483000           3793         42  0.7058824
imsparsh/lending-club-loan-dataset-2007-2011                    Lending Club Loan Dataset 2007_2011                 8802395  2020-05-28 21:29:41.447000           4468         25  0.88235295
sahilnbajaj/loans-data                                          Loans Data                                           218250  2024-04-07 15:08:37.470000           2772         37  1
jeandedieunyandwi/lending-club-dataset                          Lending Club Dataset                               28912760  2020-04-18 04:06:53.383000           4431         18  0.29411766
braindeadcoder/lending-club-data                                Lending Club data                                    218250  2019-01-11 03:24:08.830000           1573         18  0.23529412
gabrielsantello/lending-club-loan-preprocessed-dataset          Lending Club Loan - Pre-Processed Dataset          28819588  2022-07-06 15:09:21.033000           1505         23  1
utkarshx27/lending-club-loan-dataset                            Lending Club Loan Dataset                            827744  2023-05-10 05:35:45.637000           1923         16  1
janiobachmann/lending-club-first-dataset                        Lending Club First Dataset                        106124160  2019-06-04 23:44:42.543000           2026         34  0.1764706
swetashetye/lending-club-loan-data-imbalance-dataset            Lending Club Loan Data                               218250  2020-11-08 09:11:23.303000           1149          9  0.8235294
sarahvch/predicting-who-pays-back-loans                         Predicting Who Pays Back Loans                     84228523  2017-03-02 21:07:38.623000           3208         30  0.8235294
joebeachcapital/lending-club                                    Lending Club Data                                    778127  2023-08-15 05:36:56.793000            351          7  1
sahilnbajaj/lending-club-loan-data                              Lending Club loan Data                             28819588  2024-04-11 10:35:12.920000            676         10  1
deependraverma13/lending-club-loan-data-analysis-deep-learning  Lending Club Loan Data Analysis - Deep Learning      219646  2023-08-09 03:07:05.733000            682         15  1
mariiagusarova/prepared-lending-club-dataset                    Prepared Lending Club Dataset                      17787861  2022-02-25 22:31:16.543000            333          5  0.5882353
skihikingkevin/online-p2p-lending                               Online P2P Lending                                 84068740  2018-08-30 20:32:43.417000           4221         76  0.7058824
devanshi23/loan-data-2007-2014                                  loan_data_2007_2014                                62368094  2021-03-22 06:27:31.800000           2125         20  0.44117647
itssuru/loan-data                                               Loan Data                                            218250  2021-05-14 19:38:51.467000          18211        174  1

In [ ]:
!kaggle datasets download -d imsparsh/lending-club-loan-dataset-2007-2011
!unzip -q lending-club-loan-dataset-2007-2011.zip -d lending_club_real

Warning: Looks like you're using an outdated `kaggle` version (installed: 2.0.2), please consider upgrading to the latest version (2.2.2)
Dataset URL: https://www.kaggle.com/datasets/imsparsh/lending-club-loan-dataset-2007-2011
License(s): CC0-1.0
Downloading lending-club-loan-dataset-2007-2011.zip to /content
100% 8.39M/8.39M [00:00<00:00, 72.9MB/s]

In [ ]:
import os
os.listdir('lending_club_real')

['loan.csv', 'Data_Dictionary.xlsx']

In [ ]:
import pandas as pd
df = pd.read_csv('lending_club_real/loan.csv', low_memory=False)
df.shape

(39717, 111)

In [ ]:
cols = ['loan_amnt', 'term', 'int_rate', 'grade', 'sub_grade', 'emp_length',
        'home_ownership', 'annual_inc', 'purpose', 'addr_state', 'dti',
        'delinq_2yrs', 'open_acc', 'issue_d', 'loan_status']
df = df[cols]
df.shape

(39717, 15)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39717 entries, 0 to 39716
Columns: 111 entries, id to total_il_high_credit_limit
dtypes: float64(74), int64(13), object(24)
memory usage: 33.6+ MB

In [ ]:
df['int_rate'].head()
df['term'].unique()
df['home_ownership'].unique()
df['purpose'].unique()

array(['credit_card', 'car', 'small_business', 'other', 'wedding',
       'debt_consolidation', 'home_improvement', 'major_purchase',
       'medical', 'moving', 'vacation', 'house', 'renewable_energy',
       'educational'], dtype=object)

In [ ]:
df['int_rate'].head()

0    10.65%
1    15.27%
2    15.96%
3    13.49%
4    12.69%
Name: int_rate, dtype: object

In [ ]:
df['int_rate'] = df['int_rate'].str.replace('%', '').astype(float)
df['int_rate'].head()

0    10.65
1    15.27
2    15.96
3    13.49
4    12.69
Name: int_rate, dtype: float64

In [ ]:
df['term'].unique()

array([' 36 months', ' 60 months'], dtype=object)

In [ ]:
df['term'] = df['term'].str.strip()
df['term'].unique()

array(['36 months', '60 months'], dtype=object)

In [ ]:
df['home_ownership'].unique()

array(['RENT', 'OWN', 'MORTGAGE', 'OTHER', 'NONE'], dtype=object)

In [ ]:
df['emp_length'].unique()

array(['10+ years', '< 1 year', '1 year', '3 years', '8 years', '9 years',
       '4 years', '5 years', '6 years', '2 years', '7 years', nan],
      dtype=object)

In [ ]:
df['emp_length'].mode()

0    10+ years
Name: emp_length, dtype: object

In [ ]:
df['emp_length'].value_counts()

emp_length
10+ years    8879
< 1 year     4583
2 years      4388
3 years      4095
4 years      3436
5 years      3282
1 year       3240
6 years      2229
7 years      1773
8 years      1479
9 years      1258
Name: count, dtype: int64

In [ ]:
df['emp_length'] = df['emp_length'].fillna('Unknown')
df['emp_length'].value_counts()

emp_length
10+ years    8879
< 1 year     4583
2 years      4388
3 years      4095
4 years      3436
5 years      3282
1 year       3240
6 years      2229
7 years      1773
8 years      1479
9 years      1258
Unknown      1075
Name: count, dtype: int64

In [ ]:
df['loan_status'].value_counts()

loan_status
Fully Paid     32950
Charged Off     5627
Current         1140
Name: count, dtype: int64

In [ ]:
df['is_default'] = df['loan_status'] == 'Charged Off'
df['is_default'].mean()

np.float64(0.14167736737417227)

...some analysts argue that its good to exclude loans with unfinished outcome, in this case " current"

In [ ]:
finished = df[df['loan_status'] != 'Current']
finished['is_default'].mean()

np.float64(0.14586411592399617)

moves from 0.1416 to 0.145 which is a small difference. therefore I can used full dataset because the rate isnt materially affected.

In [ ]:
default_by_grade = df.groupby('grade')['is_default'].mean()
default_by_grade

grade
A    0.059693
B    0.118552
C    0.166337
D    0.210665
E    0.251583
F    0.304099
G    0.319620
Name: is_default, dtype: float64

In [ ]:
df.groupby('grade')['is_default'].count()

grade
A    10085
B    12020
C     8098
D     5307
E     2842
F     1049
G      316
Name: is_default, dtype: int64

In [ ]:
df.groupby('is_default')['annual_inc'].mean()

is_default
False    70048.707623
True     62427.298034
Name: annual_inc, dtype: float64

In [ ]:
df.groupby('purpose')['is_default'].mean()

purpose
car                   0.103292
credit_card           0.105653
debt_consolidation    0.148436
educational           0.172308
home_improvement      0.116599
house                 0.154856
major_purchase        0.101509
medical               0.152958
moving                0.157804
other                 0.158527
renewable_energy      0.184466
small_business        0.259847
vacation              0.139108
wedding               0.101373
Name: is_default, dtype: float64

Small business stands out as genuinely riskier with the 0.259 which is significantly higher than the rest. converted to percentage that is 26% defaulted.

In [ ]:
df.groupby('purpose')['is_default'].count()

purpose
car                    1549
credit_card            5130
debt_consolidation    18641
educational             325
home_improvement       2976
house                   381
major_purchase         2187
medical                 693
moving                  583
other                  3993
renewable_energy        103
small_business         1828
vacation                381
wedding                 947
Name: is_default, dtype: int64

In [ ]:
df['issue_d'].head()

0    Dec-11
1    Dec-11
2    Dec-11
3    Dec-11
4    Dec-11
Name: issue_d, dtype: object

In [ ]:
df['issue_d_dt'] = pd.to_datetime(df['issue_d'], format='%b-%y')
df['issue_d_dt'].head()

0   2011-12-01
1   2011-12-01
2   2011-12-01
3   2011-12-01
4   2011-12-01
Name: issue_d_dt, dtype: datetime64[ns]

In [ ]:
monthly = df.groupby(df['issue_d_dt'].dt.to_period('M')).agg(
    volume=('loan_amnt', 'sum'),
    count=('loan_amnt', 'count')
)
monthly

              volume  count
issue_d_dt
2007-06         7500      1
2007-07       171700     30
2007-08       208475     33
2007-09       146025     18
2007-10       318775     47
2007-11       380625     37
2007-12       986175     85
2008-01      1761050    171
2008-02      1679375    174
2008-03      2693925    236
2008-04      1556300    155
2008-05       418900     71
2008-06       379975     66
2008-07       524925     83
2008-08       412200     71
2008-09       184925     32
2008-10       780750     96
2008-11      1703450    184
2008-12      2294500    223
2009-01      2186225    239
2009-02      2341075    260
2009-03      2653250    276
2009-04      2678150    290
2009-05      3115150    319
2009-06      3192350    356
2009-07      3486450    374
2009-08      3933700    408
2009-09      4580125    449
2009-10      5611900    545
2009-11      6167225    602
2009-12      6490725    598
2010-01      6579725    589
2010-02      6784725    627
2010-03      7638325    737
2010-04      8657075    827
2010-05      9932700    920
2010-06     10474400   1029
2010-07     11183000   1119
2010-08     11185475   1078
2010-09     11233400   1086
2010-10     12163250   1132
2010-11     12503550   1121
2010-12     13714575   1267
2011-01     14824575   1380
2011-02     14585275   1297
2011-03     16503275   1443
2011-04     17522075   1562
2011-05     19062225   1689
2011-06     20808400   1827
2011-07     21271900   1870
2011-08     23149075   1928
2011-09     25762300   2063
2011-10     27392550   2114
2011-11     28105075   2223
2011-12     31519850   2260

There is a growth from June 2007 which had one loan of $ 7500 to december 2011 which has 2260 loans amounting to 31.5 million dollars.
There is a significant drop in number of loans borrowed in september 2008 as compared to the beginning of that year. This happened during the 2008 global financial crisis.
"Global credit froze as banks lost trust in each other's solvency, stopping regular lending to businesses and consumers"
Because banks were hoarding cash, they drastically tightened their lending rules. Getting approved for a loan became nearly impossible overnight.